# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.trigger_check import TriggerCheck  # noqa: E501
from openapi_client.rest import ApiException

class TestTriggerCheck(unittest.TestCase):
    """TriggerCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TriggerCheck
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.trigger_check.TriggerCheck()  # noqa: E501
        if include_optional :
            return TriggerCheck(
                metrics = openapi_client.models.metric_state.MetricState(
                    event_timestamp = 1590741878, 
                    state = 'OK', 
                    suppressed = False, 
                    suppressed_state = '0', 
                    timestamp = 1590741878, 
                    value = 70, 
                    maintenance = 56, 
                    maintenance_info = openapi_client.models.maintenance_info.MaintenanceInfo(
                        setup_user = '0', 
                        setup_time = 56, 
                        remove_user = '0', 
                        remove_time = 56, ), ), 
                score = 100, 
                state = 'OK', 
                maintenance = 56, 
                maintenance_info = openapi_client.models.maintenance_info.MaintenanceInfo(
                    setup_user = '0', 
                    setup_time = 56, 
                    remove_user = '0', 
                    remove_time = 56, ), 
                timestamp = 1590741916, 
                event_timestamp = 1590741878, 
                last_successful_check_timestamp = 1590741916, 
                suppressed = True, 
                suppressed_state = '0', 
                msg = '0', 
                trigger_id = '0'
            )
        else :
            return TriggerCheck(
        )

    def testTriggerCheck(self):
        """Test TriggerCheck"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
