# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tag_api import TagApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tag_api.TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        remove a tag  # noqa: E501
        """
        pass

    def test_get_tags(self):
        """Test case for get_tags

        get all tags  # noqa: E501
        """
        pass

    def test_get_tags_subscriptions(self):
        """Test case for get_tags_subscriptions

        get all tags and subscriptions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
