# coding: utf-8

"""
    Moira Alert

    This is an API description for Moira Alert project. Please check https://github.com/moira-alert  # noqa: E501

    The version of the OpenAPI document: 2.5.1.47
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.pattern_api import PatternApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPatternApi(unittest.TestCase):
    """PatternApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.pattern_api.PatternApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_pattern(self):
        """Test case for delete_pattern

        Deletes a Moira pattern  # noqa: E501
        """
        pass

    def test_get_all_patterns(self):
        """Test case for get_all_patterns

        Get all patterns  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
