# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.notifications_api import NotificationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_all_notification(self):
        """Test case for delete_all_notification

        deletes all available notifications  # noqa: E501
        """
        pass

    def test_delete_notification(self):
        """Test case for delete_notification

        delete a notification by id  # noqa: E501
        """
        pass

    def test_get_notifications(self):
        """Test case for get_notifications

        gets a paginated list of notifications, all notifications are fetched if end = -1 and start = 0  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
