# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.subscription_api import SubscriptionApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.subscription_api.SubscriptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        create a new subscription  # noqa: E501
        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        deletes a subscription  # noqa: E501
        """
        pass

    def test_get_subscriptions(self):
        """Test case for get_subscriptions

        get all subscriptions  # noqa: E501
        """
        pass

    def test_test_subscription_notification(self):
        """Test case for test_subscription_notification

        send test notification for a subscription  # noqa: E501
        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        update a subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
