# coding: utf-8

"""
    Moira Alert

    This is an API description for Moira Alert project. Please check https://github.com/moira-alert  # noqa: E501

    The version of the OpenAPI document: 2.5.1.47
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2003_list import InlineResponse2003List  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2003List(unittest.TestCase):
    """InlineResponse2003List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2003List
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2003_list.InlineResponse2003List()  # noqa: E501
        if include_optional :
            return InlineResponse2003List(
                metrics = ["DevOps.my_server.hdd.freespace_mbytes","DevOps.my_server.hdd.usedspace_mbytes","DevOps.my_server.db.*"], 
                pattern = 'Devops.my_server.*', 
                triggers = [
                    openapi_client.models.trigger.Trigger(
                        id = '0', 
                        name = '0', 
                        desc = '0', 
                        targets = [
                            '0'
                            ], 
                        warn_value = 1.337, 
                        error_value = 1.337, 
                        trigger_type = '0', 
                        tags = [
                            '0'
                            ], 
                        ttl_state = '0', 
                        ttl = 56, 
                        sched = openapi_client.models.subscription_sched.Subscription_sched(
                            days = [
                                openapi_client.models.subscription_sched_days.Subscription_sched_days(
                                    enabled = True, 
                                    name = '0', )
                                ], 
                            tz_offset = 56, 
                            start_offset = 56, 
                            end_offset = 56, ), 
                        expression = '0', 
                        patterns = [
                            '0'
                            ], 
                        is_remote = True, 
                        mute_new_metrics = True, 
                        throttling = 56, )
                    ]
            )
        else :
            return InlineResponse2003List(
        )

    def testInlineResponse2003List(self):
        """Test InlineResponse2003List"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
