# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse2004List(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'metrics': 'list[str]',
        'pattern': 'str',
        'triggers': 'list[Trigger]'
    }

    attribute_map = {
        'metrics': 'metrics',
        'pattern': 'pattern',
        'triggers': 'triggers'
    }

    def __init__(self, metrics=None, pattern=None, triggers=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2004List - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._metrics = None
        self._pattern = None
        self._triggers = None
        self.discriminator = None

        if metrics is not None:
            self.metrics = metrics
        if pattern is not None:
            self.pattern = pattern
        if triggers is not None:
            self.triggers = triggers

    @property
    def metrics(self):
        """Gets the metrics of this InlineResponse2004List.  # noqa: E501


        :return: The metrics of this InlineResponse2004List.  # noqa: E501
        :rtype: list[str]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this InlineResponse2004List.


        :param metrics: The metrics of this InlineResponse2004List.  # noqa: E501
        :type: list[str]
        """

        self._metrics = metrics

    @property
    def pattern(self):
        """Gets the pattern of this InlineResponse2004List.  # noqa: E501


        :return: The pattern of this InlineResponse2004List.  # noqa: E501
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this InlineResponse2004List.


        :param pattern: The pattern of this InlineResponse2004List.  # noqa: E501
        :type: str
        """

        self._pattern = pattern

    @property
    def triggers(self):
        """Gets the triggers of this InlineResponse2004List.  # noqa: E501


        :return: The triggers of this InlineResponse2004List.  # noqa: E501
        :rtype: list[Trigger]
        """
        return self._triggers

    @triggers.setter
    def triggers(self, triggers):
        """Sets the triggers of this InlineResponse2004List.


        :param triggers: The triggers of this InlineResponse2004List.  # noqa: E501
        :type: list[Trigger]
        """

        self._triggers = triggers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004List):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2004List):
            return True

        return self.to_dict() != other.to_dict()
