/* 
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NotificationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NotificationsApiTests
    {
        private NotificationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NotificationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' NotificationsApi
            //Assert.IsInstanceOf(typeof(NotificationsApi), instance);
        }

        
        /// <summary>
        /// Test DeleteAllNotification
        /// </summary>
        [Test]
        public void DeleteAllNotificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DeleteAllNotification();
            
        }
        
        /// <summary>
        /// Test DeleteNotification
        /// </summary>
        [Test]
        public void DeleteNotificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid notificationId = null;
            //var response = instance.DeleteNotification(notificationId);
            //Assert.IsInstanceOf(typeof(InlineResponse2003), response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test GetNotifications
        /// </summary>
        [Test]
        public void GetNotificationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? start = null;
            //int? end = null;
            //var response = instance.GetNotifications(start, end);
            //Assert.IsInstanceOf(typeof(NotificationsList), response, "response is NotificationsList");
        }
        
    }

}
