/* 
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * The version of the OpenAPI document: 2.5.1.47
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PatternApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PatternApiTests
    {
        private PatternApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PatternApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatternApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PatternApi
            //Assert.IsInstanceOf(typeof(PatternApi), instance);
        }

        
        /// <summary>
        /// Test DeletePattern
        /// </summary>
        [Test]
        public void DeletePatternTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pattern = null;
            //instance.DeletePattern(pattern);
            
        }
        
        /// <summary>
        /// Test GetAllPatterns
        /// </summary>
        [Test]
        public void GetAllPatternsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllPatterns();
            //Assert.IsInstanceOf(typeof(InlineResponse2003), response, "response is InlineResponse2003");
        }
        
    }

}
