/* 
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * The version of the OpenAPI document: 2.5.1.47
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TriggerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TriggerApiTests
    {
        private TriggerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TriggerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TriggerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' TriggerApi
            //Assert.IsInstanceOf(typeof(TriggerApi), instance);
        }

        
        /// <summary>
        /// Test TriggerTriggerIdGet
        /// </summary>
        [Test]
        public void TriggerTriggerIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TriggerTriggerIdGet();
            //Assert.IsInstanceOf(typeof(Object), response, "response is Object");
        }
        
        /// <summary>
        /// Test TriggerTriggerIdMetricsGet
        /// </summary>
        [Test]
        public void TriggerTriggerIdMetricsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.TriggerTriggerIdMetricsGet();
            
        }
        
        /// <summary>
        /// Test TriggerTriggerIdPut
        /// </summary>
        [Test]
        public void TriggerTriggerIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid triggerID = null;
            //Object body = null;
            //var response = instance.TriggerTriggerIdPut(triggerID, body);
            //Assert.IsInstanceOf(typeof(InlineResponse2001), response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test TriggerTriggerIdRenderGet
        /// </summary>
        [Test]
        public void TriggerTriggerIdRenderGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string targetID = null;
            //string from = null;
            //string to = null;
            //var response = instance.TriggerTriggerIdRenderGet(targetID, from, to);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
    }

}
