/**
 * Moira Alert
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class SubscriptionSchedDays {
    /**
    * Indicates if notifications should be sent on this day of the week.
    */
    'enabled'?: boolean;
    /**
    * Shortened name of the weekday
    */
    'name'?: SubscriptionSchedDays.NameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "SubscriptionSchedDays.NameEnum"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionSchedDays.attributeTypeMap;
    }
}

export namespace SubscriptionSchedDays {
    export enum NameEnum {
        Mon = <any> 'Mon',
        Tue = <any> 'Tue',
        Wed = <any> 'Wed',
        Thu = <any> 'Thu',
        Fri = <any> 'Fri',
        Sat = <any> 'Sat',
        Sun = <any> 'Sun'
    }
}
