/**
 * Moira Alert
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * The version of the OpenAPI document: 2.5.1.47
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { SubscriptionSched } from './subscriptionSched';

export class Trigger {
    'id'?: string;
    'name'?: string;
    'desc'?: string;
    'targets'?: Array<string>;
    'warnValue'?: number;
    'errorValue'?: number;
    'triggerType'?: string;
    'tags'?: Array<string>;
    'ttlState'?: string;
    'ttl'?: number;
    'sched'?: SubscriptionSched;
    'expression'?: string;
    'patterns'?: Array<string>;
    'isRemote'?: boolean;
    'muteNewMetrics'?: boolean;
    'throttling'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "desc",
            "baseName": "desc",
            "type": "string"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<string>"
        },
        {
            "name": "warnValue",
            "baseName": "warn_value",
            "type": "number"
        },
        {
            "name": "errorValue",
            "baseName": "error_value",
            "type": "number"
        },
        {
            "name": "triggerType",
            "baseName": "trigger_type",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "ttlState",
            "baseName": "ttl_state",
            "type": "string"
        },
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number"
        },
        {
            "name": "sched",
            "baseName": "sched",
            "type": "SubscriptionSched"
        },
        {
            "name": "expression",
            "baseName": "expression",
            "type": "string"
        },
        {
            "name": "patterns",
            "baseName": "patterns",
            "type": "Array<string>"
        },
        {
            "name": "isRemote",
            "baseName": "is_remote",
            "type": "boolean"
        },
        {
            "name": "muteNewMetrics",
            "baseName": "mute_new_metrics",
            "type": "boolean"
        },
        {
            "name": "throttling",
            "baseName": "throttling",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Trigger.attributeTypeMap;
    }
}

