openapi: 3.0.0
info:
  description: This is an API description for Moira Alert project. Please check https://github.com/moira-alert
  license:
    name: MIT
  title: Moira Alert
  version: 2.5.1.47
servers:
- description: Localhost server
  url: http://localhost:8080/api
tags:
- description: Runtime configuration of the API
  name: config
- description: Triggers Collection Methods
  name: triggers
- description: One Trigger Methods
  name: trigger
paths:
  /config:
    get:
      operationId: GetConfig
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Configuration fetched successfully.
      summary: Get available configuration
      tags:
      - config
  /trigger:
    put:
      operationId: CreateTrigger
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trigger'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Trigger created
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Invalid input
      summary: Create new trigger
      tags:
      - triggers
  /trigger/{triggerID}:
    get:
      operationId: GetTrigger
      parameters:
      - description: The ID of updated trigger
        example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7
        explode: false
        in: path
        name: triggerID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trigger'
          description: Trigger data
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: Trigger not found
      summary: Get an existing trigger
      tags:
      - trigger
    put:
      operationId: UpdateTrigger
      parameters:
      - description: The ID of updated trigger
        example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7
        explode: false
        in: path
        name: triggerID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trigger'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Trigger updated
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
          description: Invalid input
      summary: Update existing trigger
      tags:
      - trigger
  /trigger/{triggerID}/render:
    get:
      operationId: GetTriggerPlot
      parameters:
      - description: The ID of updated trigger
        example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7
        explode: false
        in: path
        name: triggerID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: The ID of updated target to print plot for
        example: t1
        explode: true
        in: query
        name: targetID
        required: false
        schema:
          type: string
        style: form
      - description: The start period of metrics to get
        example: -1hour
        explode: true
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
      - description: The end period of metrics to get
        example: now
        explode: true
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            image/png:
              schema:
                format: binary
                type: string
          description: Plot for trigger
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500_1'
          description: Server error
      summary: Get rendered plot for trigger
      tags:
      - trigger
  /trigger/{triggerID}/metrics:
    get:
      operationId: GetTriggerMetrics
      parameters:
      - description: The ID of updated trigger
        example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7
        explode: false
        in: path
        name: triggerID
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: The start period of metrics to get
        example: -1hour
        explode: true
        in: query
        name: from
        required: false
        schema:
          type: string
        style: form
      - description: The end period of metrics to get
        example: now
        explode: true
        in: query
        name: to
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    additionalProperties: false
                    properties:
                      step:
                        type: integer
                      ts:
                        type: integer
                      value:
                        type: number
                    type: object
                  type: array
                type: object
          description: Metrics for trigger
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500_1'
          description: Server error
      summary: Get metrics associated with certain trigger
      tags:
      - trigger
  /user:
    get:
      operationId: GetUser
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User name fetched successfully.
      summary: Gets the username of the authenticated user if it is available.
      tags:
      - user
  /user/settings:
    get:
      operationId: GetUserSettings
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: Settings fetched successfully.
      summary: Get the user's contacts and subscriptions.
      tags:
      - user
components:
  parameters:
    triggerID:
      description: The ID of updated trigger
      example: 5A8AF369-86D2-44DD-B514-D47995ED6AF7
      explode: false
      in: path
      name: triggerID
      required: true
      schema:
        format: uuid
        type: string
      style: simple
    targetID:
      description: The ID of updated target to print plot for
      example: t1
      explode: true
      in: query
      name: targetID
      required: false
      schema:
        type: string
      style: form
    from:
      description: The start period of metrics to get
      example: -1hour
      explode: true
      in: query
      name: from
      required: false
      schema:
        type: string
      style: form
    to:
      description: The end period of metrics to get
      example: now
      explode: true
      in: query
      name: to
      required: false
      schema:
        type: string
      style: form
  schemas:
    User:
      additionalProperties: false
      example:
        login: petr
      properties:
        login:
          description: Username of the authenticated user. Blank if not available.
          example: petr
          type: string
      type: object
    Contact:
      additionalProperties: false
      example:
        id: id
        type: type
        value: value
        user: user
      properties:
        type:
          type: string
        value:
          type: string
        id:
          type: string
        user:
          type: string
      type: object
    Subscription:
      additionalProperties: false
      example:
        ignore_warnings: true
        throttling: true
        ignore_recoverings: true
        sched:
          endOffset: 2
          startOffset: 5
          tzOffset: 5
          days:
          - name: name
            enabled: true
          - name: name
            enabled: true
        any_tags: true
        plotting:
          theme: theme
          enabled: true
        id: id
        user: user
        contacts:
        - contacts
        - contacts
        enabled: true
        tags:
        - tags
        - tags
      properties:
        contacts:
          items:
            type: string
          type: array
        tags:
          items:
            type: string
          type: array
        sched:
          $ref: '#/components/schemas/Subscription_sched'
        plotting:
          $ref: '#/components/schemas/Subscription_plotting'
        id:
          type: string
        enabled:
          type: boolean
        any_tags:
          type: boolean
        ignore_warnings:
          type: boolean
        ignore_recoverings:
          type: boolean
        throttling:
          type: boolean
        user:
          type: string
      type: object
    Trigger:
      additionalProperties: false
      example:
        error_value: 6.027456183070403
        expression: expression
        trigger_type: trigger_type
        patterns:
        - patterns
        - patterns
        is_remote: true
        mute_new_metrics: true
        ttl_state: ttl_state
        targets:
        - targets
        - targets
        ttl: 1
        tags:
        - tags
        - tags
        throttling: 7
        sched:
          endOffset: 2
          startOffset: 5
          tzOffset: 5
          days:
          - name: name
            enabled: true
          - name: name
            enabled: true
        warn_value: 0.8008281904610115
        name: name
        id: id
        desc: desc
      properties:
        id:
          type: string
        name:
          type: string
        desc:
          type: string
        targets:
          items:
            type: string
          type: array
        warn_value:
          type: number
        error_value:
          type: number
        trigger_type:
          type: string
        tags:
          items:
            type: string
          type: array
        ttl_state:
          type: string
        ttl:
          type: integer
        sched:
          $ref: '#/components/schemas/Subscription_sched'
        expression:
          type: string
        patterns:
          items:
            type: string
          type: array
        is_remote:
          type: boolean
        mute_new_metrics:
          type: boolean
        throttling:
          type: integer
      type: object
    inline_response_200_contacts:
      example:
        help: '@MoiraBot requires admin privileges on your target channel.'
        label: Telegram
        type: telegram
      properties:
        type:
          description: The type of contact
          example: telegram
          type: string
        label:
          description: Human readable label of the contact
          example: Telegram
          type: string
        help:
          description: Help text relevant to the contact type
          example: '@MoiraBot requires admin privileges on your target channel.'
          type: string
    inline_response_200:
      example:
        remoteAllowed: false
        contacts:
        - help: '@MoiraBot requires admin privileges on your target channel.'
          label: Telegram
          type: telegram
        - help: '@MoiraBot requires admin privileges on your target channel.'
          label: Telegram
          type: telegram
      properties:
        remoteAllowed:
          description: Flag for determining if Moira is accessible remotely.
          example: false
          type: boolean
        contacts:
          description: List of enabled contact types
          items:
            $ref: '#/components/schemas/inline_response_200_contacts'
          type: array
    inline_response_200_1:
      example:
        id: trigger_id
        message: trigger created
      properties:
        id:
          example: trigger_id
          type: string
        message:
          example: trigger created
          type: string
    inline_response_500:
      properties:
        status:
          example: Invalid request
          type: string
        error:
          example: error_value is equal to warn_value, please set exactly one value
          type: string
    inline_response_404:
      properties:
        status:
          example: Resource not found
          type: string
        error:
          example: trigger not found
          type: string
    inline_response_500_1:
      properties:
        status:
          example: Internal Server Error
          type: string
        error:
          example: 'no points found to render trigger: 5A8AF369-86D2-44DD-B514-D47995ED6AF7'
          type: string
    inline_response_200_2:
      example:
        subscriptions:
        - ignore_warnings: true
          throttling: true
          ignore_recoverings: true
          sched:
            endOffset: 2
            startOffset: 5
            tzOffset: 5
            days:
            - name: name
              enabled: true
            - name: name
              enabled: true
          any_tags: true
          plotting:
            theme: theme
            enabled: true
          id: id
          user: user
          contacts:
          - contacts
          - contacts
          enabled: true
          tags:
          - tags
          - tags
        - ignore_warnings: true
          throttling: true
          ignore_recoverings: true
          sched:
            endOffset: 2
            startOffset: 5
            tzOffset: 5
            days:
            - name: name
              enabled: true
            - name: name
              enabled: true
          any_tags: true
          plotting:
            theme: theme
            enabled: true
          id: id
          user: user
          contacts:
          - contacts
          - contacts
          enabled: true
          tags:
          - tags
          - tags
        login: petr
        contacts:
        - id: id
          type: type
          value: value
          user: user
        - id: id
          type: type
          value: value
          user: user
      properties:
        login:
          description: username of the authenticated user.
          example: petr
          type: string
        contacts:
          description: user's contacts
          items:
            $ref: '#/components/schemas/Contact'
          type: array
        subscriptions:
          description: user's subscriptions
          items:
            $ref: '#/components/schemas/Subscription'
          type: array
    Subscription_sched_days:
      example:
        name: name
        enabled: true
      properties:
        enabled:
          type: boolean
        name:
          type: string
    Subscription_sched:
      example:
        endOffset: 2
        startOffset: 5
        tzOffset: 5
        days:
        - name: name
          enabled: true
        - name: name
          enabled: true
      properties:
        days:
          items:
            $ref: '#/components/schemas/Subscription_sched_days'
          type: array
        tzOffset:
          type: integer
        startOffset:
          type: integer
        endOffset:
          type: integer
    Subscription_plotting:
      example:
        theme: theme
        enabled: true
      properties:
        enabled:
          type: boolean
        theme:
          type: string
