/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20010 struct for InlineResponse20010
type InlineResponse20010 struct {
	// current item page
	Page float32 `json:"page,omitempty"`
	// number of triggers shown per page
	Size float32 `json:"size,omitempty"`
	// total number of matching results
	Total float32 `json:"total,omitempty"`
	// list of matching triggers
	List []Trigger `json:"list,omitempty"`
}
