/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EventEventMessage struct for EventEventMessage
type EventEventMessage struct {
	Maintenance EventEventMessageMaintenance `json:"maintenance,omitempty"`
	Interval int32 `json:"interval,omitempty"`
}
