/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscriptionSchedDays struct for SubscriptionSchedDays
type SubscriptionSchedDays struct {
	Enabled bool `json:"enabled,omitempty"`
	Name string `json:"name,omitempty"`
}
