/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2003List struct for InlineResponse2003List
type InlineResponse2003List struct {
	Metrics []string `json:"metrics,omitempty"`
	Pattern string `json:"pattern,omitempty"`
	Triggers []Trigger `json:"triggers,omitempty"`
}
