/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricState struct for MetricState
type MetricState struct {
	EventTimestamp int32 `json:"event_timestamp,omitempty"`
	State string `json:"state,omitempty"`
	Suppressed bool `json:"suppressed,omitempty"`
	SuppressedState string `json:"suppressed_state,omitempty"`
	Timestamp int32 `json:"timestamp,omitempty"`
	Value float32 `json:"value,omitempty"`
	Maintenance int32 `json:"maintenance,omitempty"`
	MaintenanceInfo MaintenanceInfo `json:"maintenance_info,omitempty"`
}
