/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse500 struct for InlineResponse500
type InlineResponse500 struct {
	Status string `json:"status,omitempty"`
	Error string `json:"error,omitempty"`
}
