/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Trigger struct for Trigger
type Trigger struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Desc string `json:"desc,omitempty"`
	Targets []string `json:"targets,omitempty"`
	WarnValue float32 `json:"warn_value,omitempty"`
	ErrorValue float32 `json:"error_value,omitempty"`
	TriggerType string `json:"trigger_type,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TtlState string `json:"ttl_state,omitempty"`
	Ttl int32 `json:"ttl,omitempty"`
	Sched SubscriptionSched `json:"sched,omitempty"`
	Expression string `json:"expression,omitempty"`
	Patterns []string `json:"patterns,omitempty"`
	IsRemote bool `json:"is_remote,omitempty"`
	MuteNewMetrics bool `json:"mute_new_metrics,omitempty"`
	Throttling int32 `json:"throttling,omitempty"`
}
