/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscriptionSchedDays struct for SubscriptionSchedDays
type SubscriptionSchedDays struct {
	// Indicates if notifications should be sent on this day of the week.
	Enabled bool `json:"enabled,omitempty"`
	// Shortened name of the weekday
	Name string `json:"name,omitempty"`
}
