/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2006 struct for InlineResponse2006
type InlineResponse2006 struct {
	// list of available Moira tags, their triggers and their subscriptions
	List []TagStatistics `json:"list,omitempty"`
}
