/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ErrorBadRequest struct for ErrorBadRequest
type ErrorBadRequest struct {
	// The corresponding error status
	Status string `json:"status,omitempty"`
	// Message telling why the error occurred
	Error string `json:"error,omitempty"`
}
