/*
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * API version: 2.5.1.47
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	// username of the authenticated user.
	Login string `json:"login,omitempty"`
	// user's contacts
	Contacts []Contact `json:"contacts,omitempty"`
	// user's subscriptions
	Subscriptions []Subscription `json:"subscriptions,omitempty"`
}
