/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * API version: 2.5.1.48
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscriptionSched struct for SubscriptionSched
type SubscriptionSched struct {
	Days []SubscriptionSchedDays `json:"days,omitempty"`
	// Timezone offset in seconds (wrt GMT)
	TzOffset int32 `json:"tzOffset,omitempty"`
	StartOffset int32 `json:"startOffset,omitempty"`
	EndOffset int32 `json:"endOffset,omitempty"`
}
