/* 
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * The version of the OpenAPI document: 2.5.1.47
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Trigger
    /// </summary>
    [DataContract]
    public partial class Trigger :  IEquatable<Trigger>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Trigger" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="desc">desc.</param>
        /// <param name="targets">targets.</param>
        /// <param name="warnValue">warnValue.</param>
        /// <param name="errorValue">errorValue.</param>
        /// <param name="triggerType">triggerType.</param>
        /// <param name="tags">tags.</param>
        /// <param name="ttlState">ttlState.</param>
        /// <param name="ttl">ttl.</param>
        /// <param name="sched">sched.</param>
        /// <param name="expression">expression.</param>
        /// <param name="patterns">patterns.</param>
        /// <param name="isRemote">isRemote.</param>
        /// <param name="muteNewMetrics">muteNewMetrics.</param>
        /// <param name="throttling">throttling.</param>
        public Trigger(string id = default(string), string name = default(string), string desc = default(string), List<string> targets = default(List<string>), decimal warnValue = default(decimal), decimal errorValue = default(decimal), string triggerType = default(string), List<string> tags = default(List<string>), string ttlState = default(string), int ttl = default(int), SubscriptionSched sched = default(SubscriptionSched), string expression = default(string), List<string> patterns = default(List<string>), bool isRemote = default(bool), bool muteNewMetrics = default(bool), int throttling = default(int))
        {
            this.Id = id;
            this.Name = name;
            this.Desc = desc;
            this.Targets = targets;
            this.WarnValue = warnValue;
            this.ErrorValue = errorValue;
            this.TriggerType = triggerType;
            this.Tags = tags;
            this.TtlState = ttlState;
            this.Ttl = ttl;
            this.Sched = sched;
            this.Expression = expression;
            this.Patterns = patterns;
            this.IsRemote = isRemote;
            this.MuteNewMetrics = muteNewMetrics;
            this.Throttling = throttling;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Desc
        /// </summary>
        [DataMember(Name="desc", EmitDefaultValue=false)]
        public string Desc { get; set; }

        /// <summary>
        /// Gets or Sets Targets
        /// </summary>
        [DataMember(Name="targets", EmitDefaultValue=false)]
        public List<string> Targets { get; set; }

        /// <summary>
        /// Gets or Sets WarnValue
        /// </summary>
        [DataMember(Name="warn_value", EmitDefaultValue=false)]
        public decimal WarnValue { get; set; }

        /// <summary>
        /// Gets or Sets ErrorValue
        /// </summary>
        [DataMember(Name="error_value", EmitDefaultValue=false)]
        public decimal ErrorValue { get; set; }

        /// <summary>
        /// Gets or Sets TriggerType
        /// </summary>
        [DataMember(Name="trigger_type", EmitDefaultValue=false)]
        public string TriggerType { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets TtlState
        /// </summary>
        [DataMember(Name="ttl_state", EmitDefaultValue=false)]
        public string TtlState { get; set; }

        /// <summary>
        /// Gets or Sets Ttl
        /// </summary>
        [DataMember(Name="ttl", EmitDefaultValue=false)]
        public int Ttl { get; set; }

        /// <summary>
        /// Gets or Sets Sched
        /// </summary>
        [DataMember(Name="sched", EmitDefaultValue=false)]
        public SubscriptionSched Sched { get; set; }

        /// <summary>
        /// Gets or Sets Expression
        /// </summary>
        [DataMember(Name="expression", EmitDefaultValue=false)]
        public string Expression { get; set; }

        /// <summary>
        /// Gets or Sets Patterns
        /// </summary>
        [DataMember(Name="patterns", EmitDefaultValue=false)]
        public List<string> Patterns { get; set; }

        /// <summary>
        /// Gets or Sets IsRemote
        /// </summary>
        [DataMember(Name="is_remote", EmitDefaultValue=false)]
        public bool IsRemote { get; set; }

        /// <summary>
        /// Gets or Sets MuteNewMetrics
        /// </summary>
        [DataMember(Name="mute_new_metrics", EmitDefaultValue=false)]
        public bool MuteNewMetrics { get; set; }

        /// <summary>
        /// Gets or Sets Throttling
        /// </summary>
        [DataMember(Name="throttling", EmitDefaultValue=false)]
        public int Throttling { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Trigger {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  WarnValue: ").Append(WarnValue).Append("\n");
            sb.Append("  ErrorValue: ").Append(ErrorValue).Append("\n");
            sb.Append("  TriggerType: ").Append(TriggerType).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  TtlState: ").Append(TtlState).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  Sched: ").Append(Sched).Append("\n");
            sb.Append("  Expression: ").Append(Expression).Append("\n");
            sb.Append("  Patterns: ").Append(Patterns).Append("\n");
            sb.Append("  IsRemote: ").Append(IsRemote).Append("\n");
            sb.Append("  MuteNewMetrics: ").Append(MuteNewMetrics).Append("\n");
            sb.Append("  Throttling: ").Append(Throttling).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Trigger);
        }

        /// <summary>
        /// Returns true if Trigger instances are equal
        /// </summary>
        /// <param name="input">Instance of Trigger to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Trigger input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Desc == input.Desc ||
                    (this.Desc != null &&
                    this.Desc.Equals(input.Desc))
                ) && 
                (
                    this.Targets == input.Targets ||
                    this.Targets != null &&
                    input.Targets != null &&
                    this.Targets.SequenceEqual(input.Targets)
                ) && 
                (
                    this.WarnValue == input.WarnValue ||
                    (this.WarnValue != null &&
                    this.WarnValue.Equals(input.WarnValue))
                ) && 
                (
                    this.ErrorValue == input.ErrorValue ||
                    (this.ErrorValue != null &&
                    this.ErrorValue.Equals(input.ErrorValue))
                ) && 
                (
                    this.TriggerType == input.TriggerType ||
                    (this.TriggerType != null &&
                    this.TriggerType.Equals(input.TriggerType))
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    input.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                ) && 
                (
                    this.TtlState == input.TtlState ||
                    (this.TtlState != null &&
                    this.TtlState.Equals(input.TtlState))
                ) && 
                (
                    this.Ttl == input.Ttl ||
                    (this.Ttl != null &&
                    this.Ttl.Equals(input.Ttl))
                ) && 
                (
                    this.Sched == input.Sched ||
                    (this.Sched != null &&
                    this.Sched.Equals(input.Sched))
                ) && 
                (
                    this.Expression == input.Expression ||
                    (this.Expression != null &&
                    this.Expression.Equals(input.Expression))
                ) && 
                (
                    this.Patterns == input.Patterns ||
                    this.Patterns != null &&
                    input.Patterns != null &&
                    this.Patterns.SequenceEqual(input.Patterns)
                ) && 
                (
                    this.IsRemote == input.IsRemote ||
                    (this.IsRemote != null &&
                    this.IsRemote.Equals(input.IsRemote))
                ) && 
                (
                    this.MuteNewMetrics == input.MuteNewMetrics ||
                    (this.MuteNewMetrics != null &&
                    this.MuteNewMetrics.Equals(input.MuteNewMetrics))
                ) && 
                (
                    this.Throttling == input.Throttling ||
                    (this.Throttling != null &&
                    this.Throttling.Equals(input.Throttling))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Desc != null)
                    hashCode = hashCode * 59 + this.Desc.GetHashCode();
                if (this.Targets != null)
                    hashCode = hashCode * 59 + this.Targets.GetHashCode();
                if (this.WarnValue != null)
                    hashCode = hashCode * 59 + this.WarnValue.GetHashCode();
                if (this.ErrorValue != null)
                    hashCode = hashCode * 59 + this.ErrorValue.GetHashCode();
                if (this.TriggerType != null)
                    hashCode = hashCode * 59 + this.TriggerType.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.TtlState != null)
                    hashCode = hashCode * 59 + this.TtlState.GetHashCode();
                if (this.Ttl != null)
                    hashCode = hashCode * 59 + this.Ttl.GetHashCode();
                if (this.Sched != null)
                    hashCode = hashCode * 59 + this.Sched.GetHashCode();
                if (this.Expression != null)
                    hashCode = hashCode * 59 + this.Expression.GetHashCode();
                if (this.Patterns != null)
                    hashCode = hashCode * 59 + this.Patterns.GetHashCode();
                if (this.IsRemote != null)
                    hashCode = hashCode * 59 + this.IsRemote.GetHashCode();
                if (this.MuteNewMetrics != null)
                    hashCode = hashCode * 59 + this.MuteNewMetrics.GetHashCode();
                if (this.Throttling != null)
                    hashCode = hashCode * 59 + this.Throttling.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
