/* 
 * Moira Alert
 *
 * This is an API description for Moira Alert project. Please check https://github.com/moira-alert
 *
 * The version of the OpenAPI document: 2.5.1.47
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing EventEventMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventEventMessageTests
    {
        // TODO uncomment below to declare an instance variable for EventEventMessage
        //private EventEventMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventEventMessage
            //instance = new EventEventMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventEventMessage
        /// </summary>
        [Test]
        public void EventEventMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EventEventMessage
            //Assert.IsInstanceOf(typeof(EventEventMessage), instance);
        }


        /// <summary>
        /// Test the property 'Maintenance'
        /// </summary>
        [Test]
        public void MaintenanceTest()
        {
            // TODO unit test for the property 'Maintenance'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Test]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }

    }

}
