/* 
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004List
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004ListTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004List
        //private InlineResponse2004List instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004List
            //instance = new InlineResponse2004List();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004List
        /// </summary>
        [Test]
        public void InlineResponse2004ListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2004List
            //Assert.IsInstanceOf(typeof(InlineResponse2004List), instance);
        }


        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Test]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'Pattern'
        /// </summary>
        [Test]
        public void PatternTest()
        {
            // TODO unit test for the property 'Pattern'
        }
        /// <summary>
        /// Test the property 'Triggers'
        /// </summary>
        [Test]
        public void TriggersTest()
        {
            // TODO unit test for the property 'Triggers'
        }

    }

}
