/* 
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NotificationsListList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationsListListTests
    {
        // TODO uncomment below to declare an instance variable for NotificationsListList
        //private NotificationsListList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationsListList
            //instance = new NotificationsListList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationsListList
        /// </summary>
        [Test]
        public void NotificationsListListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NotificationsListList
            //Assert.IsInstanceOf(typeof(NotificationsListList), instance);
        }


        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Trigger'
        /// </summary>
        [Test]
        public void TriggerTest()
        {
            // TODO unit test for the property 'Trigger'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'Plotting'
        /// </summary>
        [Test]
        public void PlottingTest()
        {
            // TODO unit test for the property 'Plotting'
        }
        /// <summary>
        /// Test the property 'Throttled'
        /// </summary>
        [Test]
        public void ThrottledTest()
        {
            // TODO unit test for the property 'Throttled'
        }
        /// <summary>
        /// Test the property 'SendFail'
        /// </summary>
        [Test]
        public void SendFailTest()
        {
            // TODO unit test for the property 'SendFail'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

    }

}
