/* 
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TagStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagStatisticsTests
    {
        // TODO uncomment below to declare an instance variable for TagStatistics
        //private TagStatistics instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TagStatistics
            //instance = new TagStatistics();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TagStatistics
        /// </summary>
        [Test]
        public void TagStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TagStatistics
            //Assert.IsInstanceOf(typeof(TagStatistics), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Triggers'
        /// </summary>
        [Test]
        public void TriggersTest()
        {
            // TODO unit test for the property 'Triggers'
        }
        /// <summary>
        /// Test the property 'Subscriptions'
        /// </summary>
        [Test]
        public void SubscriptionsTest()
        {
            // TODO unit test for the property 'Subscriptions'
        }

    }

}
