/* 
 * Moira Alert
 *
 * This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>
 *
 * The version of the OpenAPI document: 2.5.1.48
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TriggerCheck
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TriggerCheckTests
    {
        // TODO uncomment below to declare an instance variable for TriggerCheck
        //private TriggerCheck instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TriggerCheck
            //instance = new TriggerCheck();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TriggerCheck
        /// </summary>
        [Test]
        public void TriggerCheckInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TriggerCheck
            //Assert.IsInstanceOf(typeof(TriggerCheck), instance);
        }


        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Test]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Maintenance'
        /// </summary>
        [Test]
        public void MaintenanceTest()
        {
            // TODO unit test for the property 'Maintenance'
        }
        /// <summary>
        /// Test the property 'MaintenanceInfo'
        /// </summary>
        [Test]
        public void MaintenanceInfoTest()
        {
            // TODO unit test for the property 'MaintenanceInfo'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'EventTimestamp'
        /// </summary>
        [Test]
        public void EventTimestampTest()
        {
            // TODO unit test for the property 'EventTimestamp'
        }
        /// <summary>
        /// Test the property 'LastSuccessfulCheckTimestamp'
        /// </summary>
        [Test]
        public void LastSuccessfulCheckTimestampTest()
        {
            // TODO unit test for the property 'LastSuccessfulCheckTimestamp'
        }
        /// <summary>
        /// Test the property 'Suppressed'
        /// </summary>
        [Test]
        public void SuppressedTest()
        {
            // TODO unit test for the property 'Suppressed'
        }
        /// <summary>
        /// Test the property 'SuppressedState'
        /// </summary>
        [Test]
        public void SuppressedStateTest()
        {
            // TODO unit test for the property 'SuppressedState'
        }
        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Test]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }
        /// <summary>
        /// Test the property 'TriggerId'
        /// </summary>
        [Test]
        public void TriggerIdTest()
        {
            // TODO unit test for the property 'TriggerId'
        }

    }

}
